# Generated by Django 2.2.1 on 2019-06-01 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=8)),
                ('phoneNumber', models.CharField(max_length=8)),
                ('direction', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=250)),
                ('photo', models.ImageField(blank=True, upload_to='webElPaso')),
            ],
        ),
        migrations.CreateModel(
            name='SizeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('4', 'Personal'), ('6', 'Pequeño'), ('8', 'Mediano'), ('12', 'Grande'), ('16', 'Familiar')], max_length=2)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webElPaso.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('quantity', models.IntegerField()),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webElPaso.Product')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webElPaso.Bill')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webElPaso.Client'),
        ),
    ]
